[package]
name = "alembic-head"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-log = "0.2.14"
tracing = "0.1.40"

[profile.dev]
opt-level = 0